### ISSUE TITLE
[Modify] Set the Web3 provider in frontend as a environment variable

### ISSUE THREAD

**Issue by kailash360** [kailash360/Snap-Stock#2]
## Is your modification request related to a problem? Please describe.

Currently, the Web3 provider in the frontend is hardcoded. This will create a problem if we wish to deploy the application on different testnets.

## Describe the modification you'd like

The Web3 provider should be set as an environment variable.

## Additional context

NA

**Comment by Aaroh1** [comment]
Hey @kailash360 sir! I had sent a PR quite some time ago. Could you please review it?

**Comment by kailash360** [comment]
Closed with #5
